---
image: node:18

variables:
  SCCACHE_DIR: ${CI_PROJECT_DIR}/.cache/sccache
  # KMS
  COSMIAN_SERVER_URL: http://localhost:9998
  KMS_PUBLIC_PATH: /tmp
  KMS_PRIVATE_PATH: /tmp
  KMS_SHARED_PATH: /tmp

stages:
  - test
  - pack
  - publish

.services:
  services:
    - name: gitlab.cosmian.com:5000/core/kms:develop_ci
      alias: kms_ci
    - redis:latest
  before_script:
    - node --version
    - npm --version
    - apt install -y curl unzip
    - ./download_wasm.sh
    - npm install

eslint:
  extends: .services
  stage: test
  script:
    - npm run format

build:
  stage: test
  extends: .services
  script:
    - npm test

example_vuejs:
  image: gitlab.cosmian.com:5000/core/ci-puppeteer:latest
  extends: .services
  stage: test
  script:
    - cd examples/vuejs
    - npm install
    - npm run build
    - npm run serve -- --port 8090 &
    - sleep 5
    - node ../test/chrome.mjs http://localhost:8090 http://localhost:9998
  artifacts:
    paths:
      - examples/vuejs/error.png
    when: on_failure
    expire_in: 1 week

example_reactjs:
  image: gitlab.cosmian.com:5000/core/ci-puppeteer:latest
  extends: .services
  stage: test
  script:
    - cd examples/reactjs
    - npm install
    - npm run build
    - npm run serve -- --port 8090 &
    - sleep 5
    - node ../test/chrome.mjs http://localhost:8090 http://localhost:9998
  artifacts:
    paths:
      - examples/reactjs/error.png
    when: on_failure
    expire_in: 1 week

example_webpack:
  extends: .services
  stage: test
  script:
    - cd examples/webpack
    - npm install
    - npx webpack

example_nodejs:
  extends: .services
  stage: test
  script:
    - cd examples/nodejs
    - npm install
    - node index.mjs 10

pack:
  stage: pack
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/

publish:
  stage: publish
  before_script:
    - npm install -g typescript
  script:
    - npm install
    - echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ~/.npmrc
    - npm publish
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
