image: node:16

variables:
  SCCACHE_DIR: ${CI_PROJECT_DIR}/.cache/sccache
  # KMS
  COSMIAN_SERVER_URL: http://localhost:9998
  KMS_PUBLIC_PATH: /tmp
  KMS_PRIVATE_PATH: /tmp
  KMS_SHARED_PATH: /tmp

stages:
  - prebuild
  - build
  - pack
  - publish
  - deploy

.services:
  services:
    - name: gitlab.cosmian.com:5000/core/kms:${KMS_VERSION}_ci
      alias: kms_ci
    - redis:latest
  before_script:
    - npm install

.test:
  stage: build
  extends: .services
  script:
    - npm test

eslint:
  extends: .services
  stage: prebuild
  script:
    - npm run format
  allow_failure: true

build_node_14:
  extends: .test
  image: node:14

build_node_16:
  extends: .test
  image: node:16

build_node_18:
  extends: .test
  image: node:18

pack:
  stage: pack
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - git archive --verbose --format=zip --output=${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip HEAD
  artifacts:
    name: '${CI_PROJECT_NAME}_${CI_COMMIT_TAG}'
    paths:
      - ${CI_PROJECT_NAME}_${CI_COMMIT_TAG}.zip
    expire_in: 3 mos

publish:
  stage: publish
  before_script:
    - npm install -g typescript
  script:
    - npm install
    - echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ~/.npmrc
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/'

deploy:
  image: docker:19.03.15
  stage: deploy
  script:
    - ssh cosmian@demo-cloudproof.cosmian.com 'mv ~/demo_cloudproof/frontend.tar ~/demo_cloudproof/frontend.tar.old'
    - docker build -f Dockerfile -t frontend .
    - docker save frontend > frontend.tar
    - scp docker-compose.yml frontend.tar run-demo.sh dump_db_demo.* cosmian@demo-cloudproof.cosmian.com:~/demo_cloudproof/
    - ssh cosmian@demo-cloudproof.cosmian.com 'bash ~/demo_cloudproof/run-demo.sh'
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/'
  when: manual
