---
# Pre-requisites:
# pip install pre-commit conventional-pre-commit
# pre-commit install
# pre-commit install --install-hooks -t commit-msg
# pre-commit autoupdate

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: dist|tests/data|tests/findex.test.ts|src/pkg|examples/full_text_search/data
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        stages: [commit]
        exclude_types:
          - yaml
          - markdown

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint-fix
        args: [--disable=MD004, --disable=MD013, --disable=MD024, --disable=MD041]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
      - id: dockerfile_lint
      - id: markdown-toc

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']

  - repo: https://github.com/crate-ci/typos
    rev: v1.16.1
    hooks:
      - id: typos

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
      - id: eslint
        args: [src, --fix]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures
      - id: fix-spaces
      - id: forbid-bidi-controls
      - id: macro-expand

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # - id: git-check
      - id: shellcheck

  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: 35be2187259c39889e2ac1936399b8a1ae6a5a00
    hooks:
      - id: flutter-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
