---
services:
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:4.19.3
    ports:
      - 9998:9998
    # To test in local with Auth0 authentication
    # environment:
    #   KMS_JWT_ISSUER_URI: https://kms-cosmian.eu.auth0.com/

  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.3.1
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
