---
# docker-compose.yml

version: '3'
services:
  kms:
    container_name: kms
    image: cosmian/kms:4.3.3
    environment:
      - KMS_HOSTNAME=0.0.0.0
      - KMS_PUBLIC_PATH=/tmp
      - KMS_PRIVATE_PATH=/tmp
      - KMS_SHARED_PATH=/tmp
    ports:
      - 9998:9998
  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.1.0
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
