# docker-compose.yml

version: "3"
services:
  kms:
    container_name: kms
    image: gitlab.cosmian.com:5000/core/kms:2.3.0_ci
    environment:
      - KMS_HOSTNAME=0.0.0.0
      - KMS_PUBLIC_PATH=/tmp
      - KMS_PRIVATE_PATH=/tmp
      - KMS_SHARED_PATH=/tmp
    ports:
      - "9998:9998"
  server:
    container_name: server
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password

  frontend:
    container_name: frontend
    image: frontend:latest
    environment:
      SERVER: /server # to play behind a reverse proxy
      # SERVER: http://127.0.0.1:3000 # to play locally
    ports:
      - 8080:8080
    depends_on:
      - server

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
