---
# docker-compose.yml

version: "3"
services:
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:4.6.0
    ports:
      - 9998:9998
    environment:
      JWK_PRIVATE_KEY:
        '{"kty": "OKP","d": "MPEVJwdRqGM_qhJOUb5hR0Xr9EvwMLZGnkf-eDj5fU8","use": "enc","crv": "X25519","kid": "DX3GC+Fx3etxfRJValQNbqaB0gs=","x":
        "gdF-1TtAjsFqNWr9nwhGUlFG38qrDUqYgcILgtYrpTY","alg": "ECDH-ES"}'
      AUTH0_TOKEN_1: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVVU1FrSVlULW9QMWZrcjQtNnRrciJ9.eyJuaWNrbmFtZSI6ImNsaWVudDEiLCJuYW1lIjoiY2xpZW50MUBjb3NtaWFuLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci84Njg5YWE1ODlmZmRkMGYzMDYzNTg3NGUzMjhhYjg3OT9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmNsLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIzLTA5LTI4VDExOjUyOjIwLjg1M1oiLCJlbWFpbCI6ImNsaWVudDFAY29zbWlhbi5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8va21zLWNvc21pYW4uZXUuYXV0aDAuY29tLyIsImF1ZCI6IkszaXhldXhuVDVrM0Roa0tocWhiMXpYbjlFNjJGRXdJIiwiaWF0IjoxNjk1OTAxOTQyLCJleHAiOjE2OTYyNjE5NDIsInN1YiI6ImF1dGgwfDY1MTU2OGY0ZjZjYzc4NzhmNzY0ZWQ0NyIsInNpZCI6ImJXbWotVVNPdi1tZmphYzBhWk5CVXZjelpHd1haY3VYIiwibm9uY2UiOiJUVGRGUkVsblMzY3pXVFF1VDNKRk9XMVdVVzFMUVU1T1VHRjBTWGxoT1VoalYxSjZkWGc1VWsxTlRBPT0ifQ.iI33WsSgWA7h2LJpkdPbhCTFfwrN-hCrn81rPJZFZ1m4PCUuKeLlNH_86Foi6WmymtLfrJmvN6n_wNHh02BsY5xEGqYlgrZmlZuIwtTucAOQqQ_Z0yjQ5c2AGsmme-Pnv60krYkmhuol_gFWFeIWvsz4CzRrxp4-FPj5gJVZVOtXYplDFl00zya2Ab-CWS1w2DiQ6ZYT9g-EG3iD63b7Q64RYW-qqizkvavtPHwPoxW_aTOPbUn1EIYCaEN5drvn6QZQQow5GjlhwSTal7nUL47700Ig5K2KCikNXW_mchWAOao13eJ-RwJooNimgcMrvkLTqjn9x_rSsxGuLc1efw"
      AUTH0_TOKEN_2: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVVU1FrSVlULW9QMWZrcjQtNnRrciJ9.eyJuaWNrbmFtZSI6ImNsaWVudDIiLCJuYW1lIjoiY2xpZW50MkBjb3NtaWFuLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci83MjZhNDZkMDdkZjY0Y2VjMDc4ZTQzNzUyYjg5MjFmMz9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmNsLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIzLTA5LTI2VDEzOjAwOjE3LjIyNVoiLCJlbWFpbCI6ImNsaWVudDJAY29zbWlhbi5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8va21zLWNvc21pYW4uZXUuYXV0aDAuY29tLyIsImF1ZCI6IkszaXhldXhuVDVrM0Roa0tocWhiMXpYbjlFNjJGRXdJIiwiaWF0IjoxNjk1NzMzMjE5LCJleHAiOjE2OTYwOTMyMTksInN1YiI6ImF1dGgwfDY1MDQ2YzdlNWEwYWZmYzg3MjAxZWE1ZiIsInNpZCI6IkstTkdIVDFqRFJRMzFiY0ZqRHdpYnZlMkRHbGxlZzZqIiwibm9uY2UiOiJaMmR5V25GMVlucG1iSE5IUmtRNGNVbzRTRXRZUVdOdFlqZFNZelZmWVU1b1l6QmxjMFUwY3pCaE53PT0ifQ.QEVI0R3LvIJuI1m3Ew0LWk29uuSF5ObznWIWw9ctlnj8BqzwUmfCs7axDpTtRkMmKkTMq3Z0EzhpefTC_pIBntA739fJMfKdO2pGBVbBVkR5r86XyELbFeqJZNEFvq3WOmSgUtjLtE121NDkaMgZr2LxEiG6d3daD2wYQ9Ust_-JxvqDRD1Ted5-jc4w4YYir9k9lnrUZIxYrUiEKKnNWkwWZP2JHnrzB_zsgwcE4K1Hii2Q2QBT_LiOawgOnf_tbX59M-3qvQXyEfAJ-iWrHKIvDP3qkf4BUVqGkiotbsCMMntyCfgwm35Wzmo2nunw72i-4bkQjh9Cz9GpikFWDA"
  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.1.0
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
