---
# docker-compose.yml

version: "3"
services:
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:4.7.0
    ports:
      - 9998:9998
    environment:
      JWK_PRIVATE_KEY:
        '{"kty": "OKP","d": "MPEVJwdRqGM_qhJOUb5hR0Xr9EvwMLZGnkf-eDj5fU8","use": "enc","crv": "X25519","kid": "DX3GC+Fx3etxfRJValQNbqaB0gs=","x":
        "gdF-1TtAjsFqNWr9nwhGUlFG38qrDUqYgcILgtYrpTY","alg": "ECDH-ES"}'
      AUTH0_TOKEN_1: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVVU1FrSVlULW9QMWZrcjQtNnRrciJ9.eyJuaWNrbmFtZSI6ImNsaWVudDEiLCJuYW1lIjoiY2xpZW50MUBjb3NtaWFuLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci84Njg5YWE1ODlmZmRkMGYzMDYzNTg3NGUzMjhhYjg3OT9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmNsLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIzLTEwLTAyVDEyOjA4OjA1LjQwMFoiLCJlbWFpbCI6ImNsaWVudDFAY29zbWlhbi5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8va21zLWNvc21pYW4uZXUuYXV0aDAuY29tLyIsImF1ZCI6IkszaXhldXhuVDVrM0Roa0tocWhiMXpYbjlFNjJGRXdJIiwiaWF0IjoxNjk2MjQ4NDkwLCJleHAiOjE2OTY2MDg0OTAsInN1YiI6ImF1dGgwfDY1MTU2OGY0ZjZjYzc4NzhmNzY0ZWQ0NyIsInNpZCI6Ik1zZlZMNHZqOVNBYnU4a3Q4ZEtJcFU3bjlxamlqeWM3Iiwibm9uY2UiOiJZakkzU2pWVllWVkpkRVp5U0c5cE0wRnhRVWgxVHpSVGRscHlSRkJLUlhweVJXMDVTM1JDT1cxMmJRPT0ifQ.rlX67uWmZwwI8-p2eCpvws3mvmQACEQlwM74LcuvbfT8tL7HjAd5YBWaI40Ty_RwpzAbJ5xS6oEO414xZid7TfEJcSRc_faHAuNzBtd050Alf4wf2kDqqjOJMvsRLS98Jtosiq9yE020BANoa_11HO5ji_ucsDaZmJLHoEPW1rNdrj6L-2eYS2vW49QFspg3-edSHeCZtTpCZ1gp_xd95afuKt_npQDLvyPr399FEv0gnZ0qLh9NGs77ltdBsEC4NrlBT8TLnYUHpQgaBserzI2AMhf2ui9DxaXULxuARB-mo4OR2MRrtcFKTYuNETv6DEPOyBLu40RLVVZEO_nc0g"
      AUTH0_TOKEN_2: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVVU1FrSVlULW9QMWZrcjQtNnRrciJ9.eyJuaWNrbmFtZSI6ImNsaWVudDIiLCJuYW1lIjoiY2xpZW50MkBjb3NtaWFuLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci83MjZhNDZkMDdkZjY0Y2VjMDc4ZTQzNzUyYjg5MjFmMz9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRmNsLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIzLTEwLTAyVDEyOjA4OjQ5LjY1M1oiLCJlbWFpbCI6ImNsaWVudDJAY29zbWlhbi5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8va21zLWNvc21pYW4uZXUuYXV0aDAuY29tLyIsImF1ZCI6IkszaXhldXhuVDVrM0Roa0tocWhiMXpYbjlFNjJGRXdJIiwiaWF0IjoxNjk2MjQ4NTM1LCJleHAiOjE2OTY2MDg1MzUsInN1YiI6ImF1dGgwfDY1MDQ2YzdlNWEwYWZmYzg3MjAxZWE1ZiIsInNpZCI6IlVCS0EyS3VlUFB4TGJnQUJ6WkItQVo4dnByeXlqSlhMIiwibm9uY2UiOiJRalV4ZEg0d2VXUmZTV05JTkVkaWVHOVVhRzFJZVZaaVZFZHRkM0pMVnk1dFZuVTFPR0ZCWDBaYU9BPT0ifQ.MGgJNRvIkJ7C11KvoIKMomkfI4nXz_-5svsSmKSk7uxv1KV0shPvn7iZXOM1EZ9K0OJHlqZLMtDyCy0l5SLDN_FKTXZGnvUbPg2wSQAD6BjocrqbZvuzqvRkcielMy9pCG8O1v4wmHBP0gKHKwIWrYD0rKqI8_vg639CksKBjefJtyvr4FvMMcuB9SmmC-nLNEFJcv9bF2OsKLB-JGbbtylbDyf2leMGORPjtxaVXQE3nuCjbaP8W8EF6TPn7GlmcRMS5UUeD4vqpIz5JniOUd_keZZkKqAZUMUG6I8Po75xQpXrcxn0AWwCgsH2tO9TObAzhPGZH_8mnADF517_IQ"
  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.1.0
    ports:
      - 9090:9090
  redis:
    image: redis:latest
    ports:
      - 6379:6379
