---
# docker-compose.yml

version: '3'
services:
  kms:
    container_name: kms
    image: ghcr.io/cosmian/kms:optional_attributes_objecttype
    ports:
      - 9998:9998
  findex_cloud:
    image: ghcr.io/cosmian/findex_cloud:0.1.0
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
