version: "3"
services:
  kms:
    image: cosmian/kms:3.0.1
    environment:
      - KMS_HOSTNAME=0.0.0.0
      - KMS_PUBLIC_PATH=/tmp
      - KMS_PRIVATE_PATH=/tmp
      - KMS_SHARED_PATH=/tmp
    ports:
      - 9998:9998

  demo:
    image: demo:latest
    ports:
      - 8080:8080
