---
name: Cloudproof Javascript Library

on:
  workflow_call:
    inputs:
      subcommands:
        required: true
        type: string
      kms-version:
        required: true
        type: string
      regression_files:
        required: false
        type: string
        default: ''

jobs:
  js-in-docker:
    runs-on: ubuntu-latest
    container: cosmian/node_ci_puppeteer

    services:
      kms:
        image: cosmian/kms:${{ inputs.kms-version }}
        env:
          COSMIAN_SERVER_URL: http://localhost:9998
          KMS_PUBLIC_PATH: /tmp
          KMS_PRIVATE_PATH: /tmp
          KMS_SHARED_PATH: /tmp

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            /github/home/.cache/puppeteer
            node_modules
            dist
            src/pkg
          key: ${{ runner.os }}-docker-node-${{ github.ref_name }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-docker-node-${{ github.ref_name }}-${{ hashFiles('package.json') }}

      - name: Test
        run: ${{ inputs.subcommands }}
        env:
          REDIS_HOST: redis
          KMS_HOST: kms

      - name: Upload non-regression test vectors
        if: inputs.regression_files != ''
        uses: actions/upload-artifact@v3
        with:
          name: cloudproof_js
          path: ${{ inputs.regression_files }}
          retention-days: 1
          if-no-files-found: error

      - name: Upload dist and source
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: cloudproof_js_${{ github.ref_name }}
          path: .
          retention-days: 1
          if-no-files-found: error
